name: Update LeetCode README

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    if: github.actor != 'github-actions[bot]'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate README
        run: |
          python scripts/update_readme.py

      - name: Commit & Push README
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md

          if git diff --cached --quiet; then
            echo "No README changes."
            exit 0
          fi

          git commit -m "🤖 Auto Update README"

          # Fetch latest branch
          git fetch origin main

          # Reset local branch to latest remote
          git reset --soft origin/main

          # Re-add README after reset
          python scripts/update_readme.py
          git add README.md

          if git diff --cached --quiet; then
            echo "README already up to date."
            exit 0
          fi

          git commit -m "🤖 Auto Update README"

          git push origin HEAD:main
