name: Update LeetCode README

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-readme
  cancel-in-progress: false

jobs:
  update-readme:
    if: github.actor != 'github-actions[bot]'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Generate README
        run: |
          python scripts/update_readme.py

      - name: Commit README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Auto Update README"
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          file_pattern: README.md
